import_report:
  name: Import Report
  description: Import daily QH CSV reports from Residual Grid Consumption.
  fields:
    entity_id:
      description: The Residual Grid Consumption entity.
      required: true
      selector:
        entity:
          integration: residual-grid-consumption
          domain: sensor
          device_class: energy
    path:
      description: The path of the CSV file.
      required: true
      selector:
        text:
