import_report:
  name: Import Report
  description: Import daily QH CSV reports from renewable energy community.
  fields:
    entity_id:
      description: The Renewable Energy Community entity.
      required: true
      selector:
        entity:
          integration: renewable energy community
          domain: sensor
          device_class: energy
    path:
      description: The path of the CSV file.
      required: true
      selector:
        text:
